### ISSUE TITLE
typing.Protocol in 3.11 needs to be backported

### ISSUE THREAD

**Issue by Gobot1234** [python/typing_extensions#104]
```py
In [6]: @runtime_checkable
   ...: class BaseBadge(Protocol):
   ...:     def __init__(self) -> None: ...

In [7]: BaseBadge.__init__
Out[7]: <function typing._no_init_or_replace_init(self, *args, **kwargs)>
```
This behaviour is not consistent with python 3.11
```pycon
>>> from typing import *
>>> @runtime_checkable
... class BaseBadge(Protocol):
...     def __init__(self) -> None: ...
... 
>>> BaseBadge.__init__
<function BaseBadge.__init__ at 0x104f249a0>
```
This may have made me slightly concerned I was loosing my sanity in a subclass today 😀

**Comment by JelleZijlstra** [comment]
This is python/cpython#31628, PR welcome.

**Comment by chrisjsewell** [comment]
Heya, I would also note that there will hopefully be another change coming, I guess in 3.12, that would be great to have backported: https://github.com/python/cpython/issues/102433
