### ISSUE TITLE
The `README.md` says PEP 702, but it is a link to PEP 698

### ISSUE THREAD

**Issue by junkmd** [python/typing_extensions#107]
https://github.com/python/typing_extensions/blob/673e5ceea32f77d90531d4d5e77a7694edba7fba/README.md?plain=1#L41

This should be

```md
  - The `@deprecated` decorator (see [PEP 702](https://peps.python.org/pep-0702/))
```

**Comment by junkmd** [comment]
If the core contributors are busy, I can fix it, but what do you think?

**Comment by srittau** [comment]
Looks like a copy-and-paste error. Any fixes welcome!

**Comment by junkmd** [comment]
Ok, I start to work on this.

**Comment by junkmd** [comment]
I PRed #108 to fix this.
