### ISSUE TITLE
Backport allowing passing an ellipsis as the last argument of Concatenate to 3.10

### ISSUE THREAD

**Issue by FasterSpeeding** [python/typing_extensions#110]
https://github.com/python/cpython/pull/30969 allowed and documented this behaviour for 3.11.

This seemingly can't be supported for <=3.9 according to https://github.com/python/typing_extensions/issues/48 but changes made by https://github.com/python/cpython/pull/30959 to the stdlib typing module lead to this behaviour erroring on later 3.10 releases when using `typing_extensions.Concatenate`.

**Comment by JelleZijlstra** [comment]
This is now documented as a limitation at https://typing-extensions.readthedocs.io/en/latest/#Concatenate. If there is a reasonable way to fix it, I'd accept a PR.
