### ISSUE TITLE
(🐞) `Literal` doesn't flatten it's arguments

### ISSUE THREAD

**Issue by KotlinIsland** [python/typing_extensions#113]
python >= 3.9 `typing.Literal` flattens it's arguments, shouldn't the one in `typing_extensions` do the same thing?

**Comment by 243f6a8885a308d313198a2e037** [comment]
Only in Python 3.8 does `Literal.__eq__` behave differently (because Python 3.8 did not confirm PEP-586, see (https://docs.python.org/3/whatsnew/3.9.html#id4 )).

For Python 3.7, `typing_extensions.Literal` seems to confirm PEP-586 (?)
