### ISSUE TITLE
Self doesn't support an async iterator protocol

### ISSUE THREAD

**Issue by erwinkinn** [python/typing_extensions#118]
Hello.
I've got a problem with Self type when using it as it's done in [types-aiofiles](https://github.com/python/typeshed/blob/3786ab295e15d4d8e77ef1512b0695bcfbb4c38f/stubs/aiofiles/aiofiles/base.pyi#L13-L14)
I've made a [merge request](https://github.com/python/typeshed/pull/9780), trying to fix it in there, but to be honest it looks like this problem relates to the async iterator protocol's support for the `tying_extensions.Self` type.
Whether it's possible to make such a thing?

**Comment by JelleZijlstra** [comment]
This seems like a mypy bug to me. `typing-extensions` doesn't really affect how type checkers interpret `Self`: the runtime `Self` object does very little. Please report your issue to mypy instead (ideally with a full, standalone sample that reproduces the bug).

**Comment by Gobot1234** [comment]
Hi, I think you've stumbled across a mypy bug, there is nothing in [PEP 673](https://peps.python.org/pep-0673) that stipulates that Self cannot be used inside of the async iterator protocol furthermore, running your code in your issue pyright there are no complaints. 
![image](https://user-images.githubusercontent.com/50501825/220207711-f843071d-ed66-4f02-b40b-ada31ebe417d.png)
Source for aiofiles stubs:
![image](https://user-images.githubusercontent.com/50501825/220207993-3ae9078d-3207-4e65-b829-0ccd1adc3074.png)

**Comment by hauntsaninja** [comment]
Make sure you're using mypy 1.0 or newer
