### ISSUE TITLE
Add minimum `typing_extensions` version for each backport

### ISSUE THREAD

**Issue by FFY00** [python/typing_extensions#121]
Now that semantic version is being used, would it be possible to document the minimum `typing_extensions` version for each of the provided backports?

**Comment by hauntsaninja** [comment]
Note that we do keep a changelog here that keeps track of when things are added or patched: https://github.com/python/typing_extensions/blob/main/CHANGELOG.md

**Comment by AlexWaygood** [comment]
I think https://github.com/python/typing_extensions/commit/024d465a38572e55a4174a7d7c0325c68f28f794 fixes this (agree, @JelleZijlstra?)

**Comment by JelleZijlstra** [comment]
Yes! This is now up at https://typing-extensions.readthedocs.io/en/latest/# but I need to add more links to it (e.g. in the README).
