### ISSUE TITLE
'typing-extensions' requires a different Python: 3.6.7

### ISSUE THREAD

**Issue by narendra92** [python/typing_extensions#127]
Am getting following error for my code which is working fine 10 days back
ERROR: Package 'typing-extensions' requires a different Python: 3.6.7 not in '>=3.7'
Please help me.

**Comment by hauntsaninja** [comment]
typing_extensions dropped support for Python 3.6 in version 4.2. You'll need to use an older version of typing_extensions than that. Note that Python 3.6 has been end of life for over a year, so I recommend against using it if possible.
