### ISSUE TITLE
Cannot parameterise `typing_extensions.Protocol` with a `ParamSpec` or `TypeVarTuple` on py310+

### ISSUE THREAD

**Issue by AlexWaygood** [python/typing_extensions#181]
> This change seems to have broken the latest version of [pydash](https://github.com/dgilland/pydash) when used with typing-extensions 4.6.0. There's a bug report about this here: https://github.com/dgilland/pydash/issues/197.

> I did a bisect of every change between typing-extensions 4.5.0 and 4.6.0, and this was pointed out as the culprit. I've had a look at the code changes here but don't have a good enough grasp of what's going wrong that is causing this to fail.

> This seems to be the relevant Pydash code that relates to the error:
https://github.com/dgilland/pydash/blob/051fe69c3e523f903a0a0ea6ca6a5c2d4b83a3e7/src/pydash/utilities.py#L577-L638

_Originally posted by @Tenzer in https://github.com/python/typing_extensions/issues/137#issuecomment-1558823709_

**Comment by AlexWaygood** [comment]
My guess is that this change might be the culprit, but haven't checked that at all: https://github.com/python/typing_extensions/pull/137/files#r1164017024

**Comment by AlexWaygood** [comment]
Minimal repro:

```pycon
>>> from typing_extensions import Protocol, ParamSpec
>>> P = ParamSpec("P")
>>> class Foo(Protocol[P]): ...
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python311\Lib\typing.py", line 344, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\typing_extensions\src\typing_extensions.py", line 672, in __class_getitem__
    raise TypeError(
TypeError: Parameters to Protocol[...] must all be type variables. Parameter 1 is ~P
```

Works fine on `typing-extensions==4.5.0` (and also works fine if you use `typing.{Protocol,ParamSpec}`. So, definitely looks like a typing_extensions bug.

**Comment by AlexWaygood** [comment]
Seems like the fundamental issue is that:
- We reimplement the logic from `typing.Generic.__class_getitem__` in `typing_extensions.Protocol.__class_getitem__`. (Ideally we wouldn't have to do this, but the `typing` module on Python 3.7 doesn't let us have `Protocol` subclass `typing.Generic`.)
- The implementation of `typing.Generic.__class_getitem__` changed on Python 3.10 and Python 3.11, but we haven't reflected those changes in `typing_extensions`.
- Prior to `typing_extensions==4.6.0`, we only re-implemented `Protocol` on Python <=3.7, but now we re-implement `Protocol` on <=3.11. This means that the latent bug has been exposed on Python 3.10 and 3.11, hence the breakage.

**Comment by JelleZijlstra** [comment]
Thanks @AlexWaygood for investigating! Are you working on a fix?

**Comment by JelleZijlstra** [comment]
No hurry, I can give it a try later today too.

We'll probably want to release a bugfix 4.6.1 with this fix.

**Comment by AlexWaygood** [comment]
One possible fix involves copying over the logic for `Generic.__class_getitem__` from 3.12a7 to `typing_extensions.Protocol.__class_getitem__`. In order to do that cleanly, though, we might have to first backport some unrelated fixes that were made to `Unpack` in 3.11, which comes with its own risks.

I looked into whether we could instead inherit from `typing.Generic` on 3.8+, which would mean we wouldn't have to have a `Protocol.__class_getitem__` on 3.8+. I'm still investigating that, but suffice it to say that there are complications to that approach as well.

**Comment by srittau** [comment]
Just leaving this here for posterity: 
![WhatsApp](https://github.com/python/typing_extensions/assets/52799/7efc60dc-411c-475c-899f-443d83857c29)

**Comment by JelleZijlstra** [comment]
They're probably mostly referring to #179, not this issue.

**Comment by srittau** [comment]
Possible, #158 would probably have been a more fitting issue for the screenshot in any case. But I claim innocence is any case. :)

**Comment by AlexWaygood** [comment]
Oh, I'm definitely guilty for _this_ bug, if we're pointing fingers 😅

I agree with @JelleZijlstra though, there seems to be far, far more breakage from https://github.com/pydantic/pydantic/issues/5821 than from this issue!

**Comment by AlexWaygood** [comment]
> I am looking into several potential fixes...
> 
> As usual with `typing_extensions`, there are several complications to grapple with :)
> 
> I also have a busy day at work, so might not be able to look at this properly until this evening!

I have a fix in the works now.
