### ISSUE TITLE
`deprecated` raises spurious `TypeError` on classes which define only `__new__`

### ISSUE THREAD

**Issue by TeamSpen210** [python/typing_extensions#192]
If `@deprecated` is applied to a class which defines `__new__` but not `__init__`, it applies [this check](https://github.com/python/typing_extensions/blob/57aae6249dd3c068a7068fd11e7d67379a544acf/src/typing_extensions.py#L2500-L2502) from `object.__new__()`, causing a `TypeError` from code that otherwise works fine:

```py
from typing_extensions import deprecated
  
@deprecated("something")
class OnlyHasNew:
     def __new__(cls, a: int, b: float) -> 'OnlyHasNew':
        obj = object.__new__(cls)
        obj.a = a
        obj.b = b
        return obj

OnlyHasNew(1, 2)  # TypeError: OnlyHasNew() takes no arguments
```

It seems like that check should be moved into the `else:` branch there. I originally found this when trying to deprecate a `NamedTuple` class, which is potentially a more likely way to run into this issue.

**Comment by JelleZijlstra** [comment]
Thanks for the report! Submitted a fix in #193.
