### ISSUE TITLE
Add get_type_hints to backport PEP 585 and 604 types in python 3.7-3.9

### ISSUE THREAD

**Issue by mauvilsa** [python/typing_extensions#221]
I have implemented an AST-based backport for PEP [585](https://www.python.org/dev/peps/pep-0585/) and [604](https://www.python.org/dev/peps/pep-0604/) types for python 3.7-3.9 to add support for this in [jsonargparse](https://github.com/omni-us/jsonargparse). See [jsonargparse/_backports.py#L134](https://github.com/omni-us/jsonargparse/blob/ecec9c44c3ffaa4c6048b481c45716bebedfe80d/jsonargparse/_backports.py#L134). It is not yet complete, a few details not generic and pending improvements based on feedback. Still, it is a start. The main question is, would there be interest in adding this to `typing-extensions`?

The desire to have this is not just jsonargparse. There is a [stackoverflow question](https://stackoverflow.com/questions/66006087/how-to-use-typing-get-type-hints-with-pep585-in-python3-8). Also see https://github.com/Lightning-AI/lightning/issues/11205. They are not able to do this because pydantic does not support it. If the backporting is available in `typing-extensions` then adding support for this in pydantic becomes was simpler.

**Comment by JelleZijlstra** [comment]
On first sight, this feels out of scope for typing-extensions. We'd have to add a fairly complicated piece of new code that doesn't directly correspond to any code in CPython. I'm worried there will be significant complexity around things like `Annotated`.
