### ISSUE TITLE
@deprecated breaking __init__ inheritance when used with mixins/multiple inheritance

### ISSUE THREAD

**Issue by recrsn** [python/typing_extensions#251]
When a class without `__init__` (mixin) is used in multiple inheritance and marked as deprecated, inheritance of `__init__` doesn't work.

Example:

```py
from typing_extensions import deprecated


class Service:
    def __init__(self, foo: str, bar: str) -> None:
        print("Service.__init__")
        self.foo = foo
        self.bar = bar

    def echo(self) -> None:
        print("Service.echo", self.foo, self.bar)


class Base:
    def message(self) -> None:
        print("Base.message")


class Child(Base):
    def message(self) -> None:
        print("Child.message")
        super().message()


@deprecated("Use Child instead")	# removing this will work normally
class FooBarPrinter(Child):
    def message(self) -> None:
        print("FooBarPrinter.message")
        super().message()


class Spam(Service, FooBarPrinter):
    def do_work(self):
        self.echo()
        self.message()


if __name__ == "__main__":
    Spam("foo", "bar").do_work()
```

**Comment by ljluestc** [comment]
from typing_extensions import deprecated


class Service:
    def __init__(self, foo: str, bar: str) -> None:
        print("Service.__init__")
        self.foo = foo
        self.bar = bar

    def echo(self) -> None:
        print("Service.echo", self.foo, self.bar)


class Base:
    def message(self) -> None:
        print("Base.message")


class Child(Base):
    def message(self) -> None:
        print("Child.message")
        super().message()


@deprecated("Use Child instead")  # removing this will work normally
class FooBarPrinter(Child):
    pass


class Spam(Service, FooBarPrinter):
    def __init__(self, foo: str, bar: str) -> None:
        super().__init__(foo, bar)  # Call the constructor of FooBarPrinter or use Base.__init__(self)
    
    def do_work(self):
        self.echo()
        self.message()


if __name__ == "__main__":
    Spam("foo", "bar").do_work()

**Comment by JelleZijlstra** [comment]
Thanks for the report (and sorry for the slow response).

`@deprecated`'s patching of classes is a bit fragile and in some cases, the best solution may be to pass `category=None` and disable the runtime DeprecationWarning. However, for this case I found a solution; PR incoming.
