### ISSUE TITLE
The git tag  3.7.4.2 is wrong

### ISSUE THREAD

**Issue by MartinThoma** [python/typing_extensions#276]
TypeAlias was added in 3.7.4.3:

```
$ pyenv local 3.6.15

$ pip install typing-extensions==3.7.4.2
$ python -c "from typing_extensions import TypeAlias"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'TypeAlias'

$ pip install typing-extensions==3.7.4.3
$ python -c "from typing_extensions import TypeAlias"
# no error
```

The commit seems to be https://github.com/python/typing_extensions/commit/d362ccb6504bf52618796822e8e6ffa9091575a4

But comparing the git tags doesn't show it: https://github.com/python/typing_extensions/compare/3.7.4.2...3.7.4.3

Comparing Github with PyPI:

* 3.7.4.3 looks fine
    * [git tag/3.7.4.3](https://github.com/python/typing_extensions/blob/3.7.4.3/typing_extensions/src_py3/typing_extensions.py) 
    * [Source distribution](https://pypi.org/project/typing-extensions/3.7.4.3/#files)
* 3.7.4.2 does not match: 
   * [git tag/3.7.4.2](https://github.com/python/typing_extensions/blob/3.7.4.2/typing_extensions/src_py3/typing_extensions.py) - contains TypeAlias
   * [Source distribution](https://pypi.org/project/typing-extensions/3.7.4.2/#files) does not contain TypeAlias

However, this makes me expect that 3.7.4.2 contains TypeAlias:

![image](https://github.com/python/typing_extensions/assets/1658117/b907f278-b1b0-455b-946e-4eb900f6f6de)

## Tracing what actually was uploaded

* [https://github.com/python/typing_extensions/commit/5848903b02dcc4f5a1efea3337109849fb41bee0#diff-f0803ded65451c15975e3661c0baf698f357eb47f32fc66f3fc6e17cea9734c6 is NOT in there
* https://github.com/python/typing_extensions/commit/fdc9359289dd0a30ca90ad9d476ecd69a93b1973 is in there

It took me longer than I want to admit to figure this out:

![image](https://github.com/python/typing_extensions/assets/1658117/46894bde-0486-4426-ae71-cb81f38703d3)

* Uploaded was d79eddef37cb09ca9a3d763364c4feb7b8473402
* Tagged was c85016137eab6d0784b76252460235638087f468
* Diff: https://github.com/python/typing_extensions/compare/d79eddef37cb09ca9a3d763364c4feb7b8473402...c85016137eab6d0784b76252460235638087f468

## Suggestion

Update the git tag to avoid other people to get confused:

```
git tag -d 3.7.4.2
git tag 3.7.4.2 d79eddef37cb09ca9a3d763364c4feb7b8473402
git push -f origin 3.7.4.2
```

**Comment by JelleZijlstra** [comment]
Nobody should be using these old versions. I'd rather not change the tag at this point.

**Comment by MartinThoma** [comment]
> Nobody should be using these old versions. I'd rather not change the tag at this point.

I agree that nobody should, but sadly people do :smile: I stumbled over this as the maintainer of pypdf. A user wanted to use it (despite mentioning that he is phasing out Python 3.6)

**Comment by JelleZijlstra** [comment]
We supported 3.6 until version 4.2.0, and 3.5 until version 4.0.0. I really don't think we need to cater to users who are stuck on such ancient versions.
