### ISSUE TITLE
Version 4.8.0rc1 fails on Python 3.7 with SyntaxError in typing_extensions.py line 874

### ISSUE THREAD

**Issue by andy-maier** [python/typing_extensions#282]
```
    from typing import SupportsIndex  # type: ignore
ImportError: cannot import name 'SupportsIndex' from 'typing' (/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/nocaselist/nocaselist/nocaselist/__init__.py", line 8, in <module>
    from ._nocaselist import *  # noqa: F403,F401
  File "/home/runner/work/nocaselist/nocaselist/nocaselist/_nocaselist.py", line 11, in <module>
    from typing_extensions import SupportsIndex  # Python <=3.7
  File "/home/runner/work/nocaselist/nocaselist/tmp_installtest/virtualenvs/nocaselist_test_test2/lib/python3.7/site-packages/typing_extensions-4.8.0rc1-py3.7.egg/typing_extensions.py", line 874
    def TypedDict(typename, fields=_marker, /, *, total=True, **kwargs):
                                            ^
SyntaxError: invalid syntax
```

Test run, for details: https://github.com/pywbem/nocaselist/actions/runs/6134182604/job/16646764117#step:19:72

Also, why does version 4.8.0rc1 even get installed? This happens during our install test, where we use different mechanisms for installing our package, and the issue happens in setup.py based install from the repo root directory. Is this another thing that broke in setup.py?

**Comment by AlexWaygood** [comment]
4.8.0rc1 no longer supports Python 3.7 (as Python 3.7 is now end-of-life), and this is stated in our pyproject.toml file:

https://github.com/python/typing_extensions/blob/df9e322f2d9cb66d936fbfeac524b5989b78cfd5/pyproject.toml#L12

**Comment by andy-maier** [comment]
Thanks for the quick response.
That explains why the error appears.

And the setup.py based install that happily installs 4.8.0rc1 on Python 3.7 is not really your problem, I guess. It is just another indicator that we should get off setup.py based installs.

As far as I'm concerned, this issue can be closed.

**Comment by AlexWaygood** [comment]
Looks like you're doing some complicated stuff here: https://github.com/pywbem/nocaselist/blob/master/tests/installtest/test_install.sh

All I can say is that `pip install typing_extensions` on Python 3.7 _should_ cause pip's resolver to pick an older version of typing_extensions, as pip looks at the `requires-python` field before selecting which version to install. That means one of the following must be going on:
1. There's a bug in pip's resolver
2. you're doing something... Strange in your script that's confusing pip's resolver somehow and meaning that it's selecting a version of typing_extensions that's incompatible with Python 3.7 :-)

I haven't looked too deeply here, but I suspect it's (2) ;-)

**Comment by andy-maier** [comment]
The pip based install process correctly does pick up an older version.
It is only the setup.py based install that ends up installing 4.8.0rc1 on Python 3.7, and the install folks have long recommended to no longer use setup.py for install.

**Comment by adenbley** [comment]
I hate to comment here, but conda-forge is still using something higher than 4.7 when it resolves.

**Comment by brianschubert** [comment]
@adenbley AFAIK, the conda forge package is maintained by a third party. If there's an issue with its metadata, you'll likely need to report it elsewhere. I think this might be the right place: https://github.com/conda-forge/typing_extensions-feedstock
