### ISSUE TITLE
Getting the error in lambads With django 3.2 

### ISSUE THREAD

**Issue by deep-kr** [python/typing_extensions#285]
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'pr_dd_to_rds': invalid syntax (typing_extensions.py, line 874)
Traceback (most recent call last):
  File "/opt/python/typing_extensions.py" Line 874
        def TypedDict(typename, fields=_marker, /, *, total=True, **kwargs):

After 18th release we start facing this issue. As our requirements are not freezed so latest version installed and lambda start falling.

**Comment by hauntsaninja** [comment]
It sounds like you're running with Python 3.7. Are you using a non-standard installer? The 4.8.0 release of typing-extensions specifies a lower bound of Python 3.8 for this reason: https://github.com/python/typing_extensions/blob/c17c499b865585458bc334a1f895ebaedd2ab854/pyproject.toml#L12

**Comment by deep-kr** [comment]
Its python 3.8 installer.

**Comment by hauntsaninja** [comment]
Yeah, that's not going to work. You should use an installer that matches the interpreter you actually run with.

**Comment by deep-kr** [comment]
You mean installer should also on 3.7. Then this 4.8 version will work.

Or i can freeze the requirement. That also works.

**Comment by JelleZijlstra** [comment]
The latest release no longer supports Python 3.7. You'll have to keep using 4.7.1.
