### ISSUE TITLE
Syntax error for typing_extensions.py, line 874invalid syntax" 

### ISSUE THREAD

**Issue by VijethKashyapTR** [python/typing_extensions#286]
I know in a recent change, typing_extensions dropped support for Python 3.7: #267
But typing_extensions is widely used by other open source library like **pg8000** and **dataclasses_json** in my case. This causes issues for me while these libraries import typing_extensions as the change was backwards incompatible.
Can we possibly make syntax a little less strict so that it works with Pyhton 3.7.

If it's not congenial at all to make these changes, we can close this issue.
Would be open for suggestions if there's any smarter way to deal with this situation

Error trace:
"Traceback (most recent call last):\n  File \"/tmp/xxxx.py\", line 9, in <module>\n    import pg8000\n  File \"/home/spark/.local/lib/python3.7/site-packages/pg8000/__init__.py\", line 1, in <module>\n    from pg8000.legacy import (\n  File \"/home/spark/.local/lib/python3.7/site-packages/pg8000/legacy.py\", line 49, in <module>\n    from pg8000.core import (\n  File \"/home/spark/.local/lib/python3.7/site-packages/pg8000/core.py\", line 9, in <module>\n    import scramp\n  File \"/home/spark/.local/lib/python3.7/site-packages/scramp/__init__.py\", line 13, in <module>\n    from importlib_metadata import version\n  File \"/home/spark/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py\", line 19, in <module>\n    from . import _adapters, _meta, _py39compat\n  File \"/home/spark/.local/lib/python3.7/site-packages/importlib_metadata/_adapters.py\", line 8, in <module>\n    from ._compat import pypy_partial\n  File \"/home/spark/.local/lib/python3.7/site-packages/importlib_metadata/_compat.py\", line 15, in <module>\n    from typing_extensions import Protocol  # type: ignore\n  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 963, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 906, in _find_spec\n  File \"<frozen importlib._bootstrap_external>\", line 1280, in find_spec\n  File \"<frozen importlib._bootstrap_external>\", line 1254, in _get_spec\n  File \"<frozen importlib._bootstrap_external>\", line 1235, in _legacy_get_spec\n  File \"<frozen importlib._bootstrap>\", line 441, in spec_from_loader\n  File \"<frozen importlib._bootstrap_external>\", line 594, in spec_from_file_location\n  File \"/tmp/glue_deps.zip/typing_extensions.py\", line 874\n    def TypedDict(typename, fields=_marker, /, *, total=True, **kwargs):\n                                            ^\nSyntaxError: invalid syntax"

https://github.com/python/typing_extensions/pull/267/files#r1254741967
![image](https://github.com/python/typing_extensions/assets/84446039/bd23d5d0-f771-4094-a12c-96ad188a7ff5)

**Comment by VijethKashyapTR** [comment]
@AlexWaygood @JelleZijlstra

**Comment by hauntsaninja** [comment]
Nope, see https://github.com/python/typing_extensions/issues/285. If you need to use Python 3.7, make sure you use a standard installer whose version matches that of your runtime, and the installer will resolve a version of typing-extensions that is compatible with 3.7, namely typing-extensions 4.7.1 or earlier
