### ISSUE TITLE
Referencing to bases of TypeVar

### ISSUE THREAD

**Issue by valq7711** [python/typing_extensions#301]
Hi! Is there a working equivalent to the following: 
```python
T = TypeVar('T')

def some() -> type[Union[*T.__bases__]]:  
    ...
```
thanks in advance

**Comment by JelleZijlstra** [comment]
I assume you mean something like this?

```python
def some(x: T) -> type[???]:
    for base in type(x).__bases__:
        return base
```
Then no, that's not supported. A new type system feature for this should be discussed at https://github.com/python/typing, not here.
