### ISSUE TITLE
PEP 585 + PEP 604 support

### ISSUE THREAD

**Issue by bswck** [python/typing_extensions#315]
Yes, you've read that right!
[PEP 585](https://peps.python.org/pep-0585/) and [PEP 604](https://peps.python.org/pep-0604/) backports for Python 3.8 and 3.9, respectively.

I've implemented a safe backport that scans AST of type hints and checks classes in the namespaces during evaluation to resolve how to replace them to make it possible to evaluate them in `typing.get_type_hints()`.

For more details including a technical explanation and the source code, check out [bswck/modern_types](https://github.com/bswck/modern_types).

Would you be interested in incorporating these backports to `typing_extensions`?

My idea would be to export a subclass of `ForwardRef` and then pretty much the same stuff as in my aforementioned implementation, additionally exporting these: https://github.com/python/typing_extensions/blob/d6dc4f157e731b2475141aae0c2586ed0243b686/src/typing_extensions.py#L3013-L3050 with PEP 604 support—using the technique from https://github.com/bswck/modern_types/blob/812caf3ca7fd77b467a3acf853ee3dbe3686e35e/__modern_types__/_registry.py#L30-L231.

Incorporating the backports would be ideal, because no monkeypatching would have to occur (`__modern_types__` reassigns `typing.ForwardRef._evaluate` with a custom implementation).

**Comment by mikeshardmind** [comment]
Guess I'll followup here from the original discussion in discord: Personally, I think this would be better suited as `typing_extensions.get_type_hints_ignore_unknown_generics`, and be a function that could be used as desired that did this rather than an approach that uses monkeypatching of the standard library, which has global effects that not every library will be aware of.

**Comment by bswck** [comment]
> rather than an approach that uses monkeypatching of the standard library, which has global effects that not every library will be aware of.
The suggested backport would introduce no monkeypatching to the standard library, as I've already mentioned above:
> Incorporating the backports would be ideal, because no monkeypatching would have to occur (__modern_types__ reassigns typing.ForwardRef._evaluate with a custom implementation).

**Comment by mikeshardmind** [comment]
> The suggested backport would introduce no monkeypatching to the standard library, as I've already mentioned above
[...]
> My idea would be to make a subclass of ForwardRef and then pretty much the same stuff as in my aforementioned implementation.

As already discussed in discord, the primary source of ForwardRef instances is not from direct user instantiation of them, simply providing a subclass with different  `._evaluate` is insufficient to allow this in forward references, there has to be a mechanism to handle annotations with this. I'm sorry I missed that you're no longer monkey patching at all when initially going to respond, but that only raises further questions about providing a subclass and not an alternative functional method for evaluating/getting type hints with support for future syntax in forward references.

**Comment by JelleZijlstra** [comment]
I may have to look into this in more detail, but I'm not enthusiastic. @mikeshardmind is right that direct instantiation of ForwardRef is not an important use case. This approach also won't fix PEP 585/604 usage outside of annotations, e.g. in `TypeVar` bounds, casts, type aliases.

**Comment by bswck** [comment]
For instance, take a look at https://fastapi.tiangolo.com/advanced/additional-status-codes/#additional-status-codes_1.
Patching `typing_extensions` to work with the new `ForwardRef`s would really simplify this `Union[X, Y]` vs `X | Y` discrepancy and be easier to learn for the new Python programmers that `X | Y` is the way to go.
Even apart from this, it can save the extra time spent on importing deprecated things from `typing`.

**Comment by bswck** [comment]
Observation: the current implementation does not fully implement PEP 604, because cases like `int | None` are not handled (`int` is not replaced by any object).

**Comment by DanCardin** [comment]
For reference, (and for unrelated reasons,) I have a PR that [duplicates ForwardRef](https://github.com/python/typing_extensions/pull/312/files) into typing_extensions using the implementation as of 3.11. Due to it being `Final`, I found it necessary to copy the whole implementation rather than subclass it.

In my experience, it was not trivial to extricate. Although the fact that doing so revealed several ways in which the <3.11 featureset was quite different, to the point that it seemed like it **was** a valuable exercise if it meant that `typing_extensions` would be able to backport the current-version behavior of `get_type_hints` entirely.

**Comment by bswck** [comment]
Closing this for now. I'm working on https://github.com/alexmojaki/eval_type_backport with @alexmojaki. Feel free to reopen this if you would like me to work on this in typing extensions.

**Comment by alexmojaki** [comment]
@DanCardin I just came across https://github.com/DanCardin/cappa/pull/100. I see you added your own version of `get_type_hints` that's very similar to (~ copied from?) the one in pydantic, i.e. it uses `eval_type_backport` and handles compatibility for ForwardRefs. Is it fair to say that if this version of `get_type_hints` existed in `typing_extensions` you could just use that directly and it would have saved you some trouble?
