### ISSUE TITLE
Documentation does not work with intersphinx (missing module name)

### ISSUE THREAD

**Issue by arthur-tacca** [python/typing_extensions#341]
The documentation for `typing_extensions` cannot be referred to from other documentation through intersphinx because it lacks a module name declaration. For example, other docs may look for `typing_extensions.Unpack` but find only the non-matching identifier `Unpack` here. Hopefully you are sympathetic considering that `typing_extensions` uses intersphinx itself (for referencing the core Python docs) :-)

The simple fix is to add the following to `doc/index.rst` on a line of its own (at the very start would be conventional):

```rst
.. module:: typing_extensions
```

This does have a knock-on impact that all the identifiers in the documentation will be prefixed with it (e.g. `class NamedTuple` would show as `class typing_extensions.NamedTuple`). Arguably this is an improvement as it's more consistent with most other docs, but if it's not desired then the following can be added to `doc/conf.py` (perhaps in the "General configuration" section):

```py
add_module_names = False
```

**Comment by arthur-tacca** [comment]
For comparison, this is the docs produced with or without the namespace name. (The one without was produced using `add_module_names = False` as mentioned above.)

<img width="493" alt="typing_extensions docs original" src="https://github.com/python/typing_extensions/assets/20324099/c4e4dabc-deab-4dc4-bf0d-a5c06a6c496e">

<img width="493" alt="typing_extensions docs with namespace" src="https://github.com/python/typing_extensions/assets/20324099/3af6ad30-ba32-4c3b-b40b-8eda3b8e29a0">

**Comment by AlexWaygood** [comment]
> This does have a knock-on impact that all the identifiers in the documentation will be prefixed with it (e.g. `class NamedTuple` would show as `class typing_extensions.NamedTuple`).

This feels somewhat redundant to me, since we only ship a single module (`typing_extensions`), so all objects documented would have the same prefix in the docs. So I personally have a slight preference towards the `add_module_names = False` option you mentioned.
