### ISSUE TITLE
Python 3.13a4: ``_Py_atomic_load_ssize_relaxed``: identifier not found

### ISSUE THREAD

**Issue by wjakob** [python/typing_extensions#345]
Dear CPython team,

I bumped the nanobind test suite build matrix to include 3.14a4. This works except for compilation on windows via MSVC, which fails with an error complaining that ``_Py_atomic_load_ssize_relaxed`` is not defined. 

```
C:\hostedtoolcache\windows\Python\3.13.0-alpha.4\x64\include\object.h(433,5): error C3861: '_Py_atomic_store_ssize_relaxed': identifier not found
```

Link: https://github.com/wjakob/nanobind/actions/runs/8087892173/job/22100798452

I think that including `Python.h` from an extension is all that's needed to trigger this. I know that there has been a lot of activity in this part of the code related to free-threading. But I am not creating a free-threading build.

**Comment by AlexWaygood** [comment]
Did you mean to file this issue over at CPython, by any chance? I can transfer it over, if so

**Comment by wjakob** [comment]
Ouch, sorry. I will create a new issue there.
