### ISSUE TITLE
`AttributeError` if you mix `typing.Protocol` with `typing_extensions.runtime_checkable` on py312+

### ISSUE THREAD

**Issue by banderlog** [python/typing_extensions#372]
Hi, during the investigation of https://github.com/dbrattli/OSlash/issues/35 I came across you.

The problem in combination of python and typing_extensions versions:
- `~=python-3.12.0` with `typing-extensions>4.9.0` fails with `AttributeError: no attribute _non_callable_proto_members_`
- `~=python-3.10.0` and `~=python-3.11.0` works fine with `typing-extensions>=4.9.0`

**Comment by AlexWaygood** [comment]
Thanks for the report — are you able to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) ? Unfortunately it'll be very hard for us to help you otherwise :-)

**Comment by AlexWaygood** [comment]
Please also copy and paste the full traceback from your terminal. It's impossible for us to know what might be causing this error if you only give us the last line :-)

**Comment by banderlog** [comment]
> Thanks for the report — are you able to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Unfortunately it'll be very hard for us to help you otherwise :-)

```python
from typing import TypeVar, Generic, Protocol
from typing_extensions import runtime_checkable


TState = TypeVar("TState")
TSource = TypeVar('TSource', covariant=True)


class State(Generic[TSource, TState]):
    def foo(x):
        pass


@runtime_checkable
class Functor(Protocol[TSource]):
    def foo(x):
        pass

assert issubclass(State, Functor)
```

**Comment by banderlog** [comment]
> Please also copy and paste the full traceback from your terminal. It's impossible for us to know what might be causing this error if you only give us the last line :-)

I am afraid that it will not help you much:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/venv/lib/python3.12/site-packages/my_module/_main_.py", line 3, in <module>
    import jsonrpcserver
  File "/venv/lib/python3.12/site-packages/jsonrpcserver/_init_.py", line 19, in <module>
    from .async_main import (
  File "/venv/lib/python3.12/site-packages/jsonrpcserver/async_main.py", line 5, in <module>
    from .async_dispatcher import dispatch_to_response_pure
  File "/venv/lib/python3.12/site-packages/jsonrpcserver/async_dispatcher.py", line 9, in <module>
    from oslash.either import Left  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/oslash/_init_.py", line 11, in <module>
    from .state import State
  File "/venv/lib/python3.12/site-packages/oslash/state.py", line 78, in <module>
    assert issubclass(State, Functor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 1841, in _subclasscheck_
    cls._non_callable_proto_members_
AttributeError: type object 'Functor' has no attribute '_non_callable_proto_members_'
```

**Comment by AlexWaygood** [comment]
Thanks. This happens because you're mixing `typing.Protocol` with `typing_extensions.runtime_checkable`. If you either import both symbols from `typing` or both symbols from `typing_extensions`, the error goes away.

That doesn't mean that there isn't necessarily a bug for us to fix here, but it might provide you with a workaround in the meantime

**Comment by banderlog** [comment]
I see, thanks for operative response!)

**Comment by AlexWaygood** [comment]
Smaller reproducer:

```py
from typing import Protocol
from typing_extensions import runtime_checkable

@runtime_checkable
class Functor(Protocol): ...

issubclass(object, Functor)
```
