### ISSUE TITLE
Add an `override` decorator to a .pyi file

### ISSUE THREAD

**Issue by IvanKirpichnikov** [python/typing_extensions#406]

**Comment by JelleZijlstra** [comment]
You can use `@typing_extensions.override` in a pyi file, provided your type checker is updated. What else are you asking for?

**Comment by IvanKirpichnikov** [comment]
Pycharm swears that there is no link to override in typing_extensions.pyi

complete error 'Cannot find reference 'override' in 'typing_extensions.pyi''
System: Windows 11
python: python 3.11.8:db85d51

**Comment by JelleZijlstra** [comment]
That sounds like a problem with PyCharm. They likely have bundled a stub file for typing-extensions that isn't updated.

**Comment by srittau** [comment]
This is probably best reported to the PyCharm tracker at https://youtrack.jetbrains.com/issues.

FWIW, it works for me with PyCharm Pro 2024.1.1 and typing_extensions

**Comment by srittau** [comment]
@IvanKirpichnikov Also, please make sure that typing_extensions is actually installed into your current environment (e.g. using `pip install typing_extensions`).

**Comment by IvanKirpichnikov** [comment]
> @IvanKirpichnikov Also, please make sure that typing_extensions is actually installed into your current environment (e.g. using `pip install typing_extensions`).

I checked for it and moreover tried to update it. Alas, it did not help
