### ISSUE TITLE
Weird conflict between typing-extensions 4.12.1, xarray, dirty_equals on Python 3.8

### ISSUE THREAD

**Issue by soxofaan** [python/typing_extensions#425]
FYI: I just created this ticket https://github.com/samuelcolvin/dirty-equals/issues/99  against the dirty-equals project about weird import breakage when combining xarray, dirty_equals and recently released typing-extensions 4.12.1 on Python 3.8.

On second thought it might be better to file this against the typing-extensions project

**Comment by AlexWaygood** [comment]
We fixed this in https://github.com/python/typing_extensions/commit/53bcdded534494674f893112f71d3be344d65363... @JelleZijlstra, maybe we should do a patch release?

(Do I have the power to do that now? I didn't with the old workflow, but maybe I can after https://github.com/python/typing_extensions/commit/63d827754489f307630dea2e0f58dfab65837a66... If so, I'm happy to do it.)

**Comment by JelleZijlstra** [comment]
Yes, you should be able to do a patch release, go ahead!
