### ISSUE TITLE
[bug][4.12.2] ImportError: cannot import name 'TypeIs' from 'typing_extensions' 

### ISSUE THREAD

**Issue by nctu6** [python/typing_extensions#454]
Neither of the following conditions includes a TypeIs variable in typing_extensions.py:

1. Installing typing_extensions via pip (which installs version 4.12.2).
2. The source code available at https://github.com/python/typing_extensions/archive/refs/tags/4.12.2.zip.

Regards.

**Comment by srittau** [comment]
This is strange. The zip you linked to clearly has `TypeIs` defined and it's also included in `__all__`. I can verify locally that I can import `TypeIs` either by naming it or using a star import. Are you sure that the correct version of typing\_extensions is picked up? Does the output of the following script point to the right location?

```python
import typing_extensions

print(typing_extensions.__file__)
```

**Comment by nctu6** [comment]
I have found that there is no issue with the 4.12.2 zip file. It appears to be an installation problem with my testing environment.

Thank you very much.
Regards.
