### ISSUE TITLE
Add a covariant `Mapping`-like type

### ISSUE THREAD

**Issue by harahu** [python/typing_extensions#5]
## What

I want a new protocol added to `typing` or `typing_extensions`, expressing the aspects of `Mapping` that are covariant with regards to the key type. That is, the `Mapping` type, but without the `__getitem__` and `get` methods.

Something along the lines of:

```py
class CovariantMappingLike(Protocol[KT_co, VT_co]):
    # A better name for this protocol might be needed
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def keys(self) -> KeysView[KT_co]: ...
    def items(self) -> ItemsView[KT_co, VT_co]: ...
    def values(self) -> ValuesView[VT_co]: ...
```
## Why

`Mapping`s are often, in practice, treated in ways that make them covariant with regards to key. A specific example is laid out in a comment of mine found here: https://github.com/python/typing/issues/445#issuecomment-1131413084

The `Mapping` type, however, cannot be covariant w. regards to key, as it also implements methods that don't allow for it (`__getitem__` and `get`) to be covariant.

This leaves me unable to express, in a simple and idiomatic way, that I intend to use a `Mapping` in a way that respects covariance.

Being able to write:
```py
def foo(mapping: CovariantMappingLike[Hashable, Hashable]) -> int:
    ...
```

_would_ allow me to express what I'm after. It would allow me to express: "Give me a mapping, but I promise to not be looking up keys on it."

This, again, makes it possible to have narrower key types for my `Mapping` objects, as I can pass a narrowly typed `Mapping` to `foo`, without casting:

```py
my_map: Dict[Literal["foo", "bar", "baz"], str] = {}

# I want this to be fine
foo(my_mapping)
```

_I was prompted by @srittau to create this issue in https://github.com/python/typing/issues/445#issuecomment-1131458824_

**Comment by gvanrossum** [comment]
I feel this is too rarely needed to add here. You can just define a protocol in your own code.

**Comment by harahu** [comment]
> I feel this is too rarely needed to add here. You can just define a protocol in your own code.

The need to interact co-variantly with mapping keys seems pretty common to me. See:
- https://github.com/python/typing/issues/445
- https://github.com/python/mypy/issues/1114

This type can be used for every function that interacts with a mapping without looking up values, i.e. covering all "safe" use-cases of what's suggested in the issues mentioned above. That's a pretty good compromise solution IMO.

The Mapping stubs in typeshed can also be defined based on this type, making for a neat simplification, and also isolates the part of the Mapping API that leads to invariance, which, I think, is a good idea.

**Comment by gvanrossum** [comment]
If we have to have it, maybe CovariantMapping?

**Comment by harahu** [comment]
> If we have to have it, maybe CovariantMapping?

One objection to that name is that it can sound a bit like a subtype of Mapping. But in this case it's a supertype. Not sure how to convey that elegantly.

**Comment by gvanrossum** [comment]
I don't think you can get the perfect name, so I recommend not overthinking it.

**Comment by hmc-cs-mdrissi** [comment]
My main question is when would you choose covariant mapping vs mapping with a typevar for key? What's difference between,

```python
def foo(mapping: CovariantMapping[Hashable, Hashable]):
  ...
```

vs

```python
HashableT = TypeVar('HashableT', bound=Hashable)

def foo(mapping: CovariantMapping[HashableT, Hashable]):
  ...
```

I occasionally use latter as a way to make an invariant type argument behave as if it were covariant.

**Comment by harahu** [comment]
> I occasionally use latter as a way to make an invariant type argument behave as if it were covariant.

I have, and am using the same pattern. But it is both more verbose, and harder to understand for the reader.

Given that most documentation for `TypeVar`s showcase their purpose as illustrating dependencies between types in _more than one location_, I think one need to expect the reader to have a pretty strong understanding of the concept before they'll be able to effortlessly read you second example.

**Comment by carljm** [comment]
I agree that the need for a mapping type that is covariant in its key does come up regularly, but a mapping protocol that doesn't implement `__getitem__` at all seems too limited; is it really that common to use a mapping and never index into it? The common use cases would seem to be limited to when you are just iterating over the keys and values in the mapping, or comparing it to another mapping. Indexing seems pretty fundamental to what it means to be a mapping.

I think a more useful "covariant in keys" mapping type would be one that does provide `__getitem__` but has it accept `object` instead of the key type, as originally proposed as option 2 in https://github.com/python/typing/issues/445. Without typechecker special casing, this means you effectively give up type-checking of indices (so the type checker won't catch `m[3]` as an error if `m: CovariantMapping[str, str]`), but it allows the mapping to be covariant in the key type and still permit indexing.

I think it's too late to make this change for `Mapping`, but if we do introduce a new `CovariantMapping`, I think it would be more useful this way.

**Comment by JelleZijlstra** [comment]
Closing this following the policy to only include things that are in CPython or in a PEP.

**Comment by harahu** [comment]
> Closing this following the policy to only include things that are in CPython or in a PEP.

Is there an alternative location where these non-PEP, but generally usable types could be shared?
