### ISSUE TITLE
[bug][4.12.2][Notebook] cannot import name 'TypeIs' from 'typing_extensions'

### ISSUE THREAD

**Issue by sl-ffx** [python/typing_extensions#510]
I am using Fabric Notebook and I want to use the `openai` package but I get an error on importing it. (installing `openai` with `--upgrade` also upgrades `typing_extensions` to version 4.12.2)
```bash
!pip install openai --upgrade
```
```python
import openai
```
```
ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/typing_extensions.py)
```

The same error occurs on importing `TypeIs`.
```python
from typing_extensions import TypeIs
```

The weird thing is, that the `/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/typing_extensions.py` contains the `TypeIs` in the `__all__` variable but when I execute the following code I cannot find `TypeIs` in the resulting array.
```python
import typing_extensions
dir(typing_extensions)
```

I am using typing_extensions v4.12.2 and python v3.11.8
```bash
!pip show typing_extensions
!python --version

Name: typing_extensions
Version: 4.12.2
Summary: Backported and Experimental Type Hints for Python 3.8+
Home-page: 
Author: 
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
License: 
Location: /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages
Requires: 
Required-by: alembic, azure-core, azure-storage-blob, azure-storage-file-datalake, dash, huggingface_hub, lightning-utilities, mypy, nni, openai, pydantic, pydantic_core, pytorch-lightning, SQLAlchemy, torch, typeguard
Python 3.11.8
```

I've run out of ideas on how to solve the problem. It worked yesterday and today I cannot import it any longer.

This has to be an issue with Fabric Notebook because everything works fine locally on my device. But maybe you have an idea how to solve it in Notebook.

**Comment by srittau** [comment]
This sounds like an environmental problem where the wrong version of the library is picked up. You could check that by printing `typing_extensions.__file__` and see whether the correct file is picked up.

**Comment by sl-ffx** [comment]
```python
import typing_extensions

print(typing_extensions.__file__)
```
```
/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/typing_extensions.py
```

That's the same file as mentioned above.

**Comment by hauntsaninja** [comment]
It's probably already imported in your notebook process by the time you install the newer version

There's not really anything we can do to help you in this issue tracker

**Comment by sl-ffx** [comment]
Thanks for your feedback. I solved the problem and want to add the information here if someone else has the same problem:

I contacted the support of Fabric and they responded with the following suggestion:
> Could you please use %pip install openai instead of ! pip install openai.
> 
> We recommend %pip instead of !pip. !pip is an IPython built-in shell command, which has the following limitations:
> !pip only installs a package on the driver node, not executor nodes.
> Packages that install through !pip don't affect conflicts with built-in packages or whether packages are already imported in a notebook.

To solve the problem I had to replace
```python
!pip install openai --upgrade
```
with
```python
%pip install openai --upgrade
```

**Comment by robertohj** [comment]
I can confirm that this solution worked. I was having the same error but in a slightly different scenario. I was installing mlflavors in a Fabric notebook, and using !pip install throw the error, while installing with %pip did not. Huge tip right there, @sl-ffx, thanks!
