### ISSUE TITLE
Missing tag for 4.3.0?

### ISSUE THREAD

**Issue by mgorny** [python/typing_extensions#54]
I see there's a 4.3.0 typing-extensions release on pypi. Could you push the corresponding tag here?

**Comment by JelleZijlstra** [comment]
Thanks for noticing! I just pushed the tag.

I noticed we lost tags for previous releases in the repo split. I'll try to add a few recent ones too.

**Comment by JelleZijlstra** [comment]
https://github.com/python/typing_extensions/tags now has releases from 3.10.0.0 onwards.

**Comment by mgorny** [comment]
Thanks!
