### ISSUE TITLE
Add support for runtime type checking

### ISSUE THREAD

**Issue by matthewwardrop** [python/typing_extensions#59]
Greetings!

I'd love to see `typing_extensions` add support for runtime type validation. There are *so* many different implementations of this, all with pitfalls or differences, and having a standard runtime checker co-located with the type definitions themselves makes a lot of sense to me.

I'm imagining an additional public boolean function (perhaps with supporting private methods) that checks whether a given object satisfies a given type. For example:

```
>>> from typing_extensions import isinstanceof
>>> isinstanceof("my string", str)
True
>>> isinstanceof("my string", Union[str, int])
True
>>> isinstanceof("hi", Literal[1, "bye"])
False
```
And so on.

Is this something that others might consider in scope for this project?

**Comment by hauntsaninja** [comment]
Thanks, but this is out of scope for typing-extensions. As a top 10 most downloaded package, it's important to keep scope focussed.

If you're interested in standardising approaches taken by runtime type checkers, the typing-sig mailing list, https://github.com/python/typing or the bug trackers of existing runtime type checkers are good places to discuss that.
