### ISSUE TITLE
CLA bot?

### ISSUE THREAD

**Issue by srittau** [python/typing_extensions#66]
Currently, this repository is not covered by the CLA bot. This is now a requirement for repositories under /python. How can we set it up?

Also, if I understand correctly, all contributions since the split are not covered by the CLA. How can we retroactively make them covered by the CLA? This only affects contributions by the following authors, so it shouldn't be a big deal:

```
Author: Alex Waygood <Alex.Waygood@Gmail.com>
Author: Jelle Zijlstra <jelle.zijlstra@gmail.com>
Author: Sebastian Rittau <srittau@rittau.biz>
```

**Comment by srittau** [comment]
Cc @JelleZijlstra @AlexWaygood

**Comment by AlexWaygood** [comment]
Setting up a CLA bot for this repo sounds fine! I haven't got any insight as to how we might do that, or if it's possible for contributions to be "retroactively" covered by the CLA. However, I can confirm that I signed the CLA long before making my `typing_extensions` contributions!

**Comment by srittau** [comment]
For reference: https://github.com/apps/cpython-cla-bot/ is the GitHub App. Maybe Jelle can configure it for this repository or maybe someone from the SC should do it? Cc @encukou

**Comment by encukou** [comment]
Please ping `@python/organization-owners` if Jelle doesn't have the permission.

**Comment by JelleZijlstra** [comment]
I tried but it failed with `This action must be performed by an organization owner`. @python/organization-owners could you go from https://github.com/apps/cpython-cla-bot/ to add the CLA bot to the `python/typing_extensions` repo?

**Comment by ambv** [comment]
Due to the controls being kind of silly, the bot app is already configured for *all* repositories in `python/`. It's only disabled in the configuration of the actual tool to not react to repositories outside of a predefined list. I'll add typing_extensions.

**Comment by ambv** [comment]
Aaand it's done.

**Comment by JelleZijlstra** [comment]
Thanks @ambv, I confirmed it works on #49.
