### ISSUE TITLE
Backport generic NamedTuple and TypedDict support

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing_extensions#7]
Python 3.11 will support generic NamedTuples (python/cpython#92027) and TypedDicts (python/cpython#27663) at runtime. If there is community interest, we should backport support for these features into typing-extensions. I'm not planning to work on this myself but I'll accept patches.

**Comment by julien-blanchon** [comment]
I love this ! I hope TypedDict will also be include soon. Thanks you @JelleZijlstra @AlexWaygood
