### ISSUE TITLE
get_overloads and clear_overloads are missing from typing_extensions.pyi 

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [python/typing_extensions#70]
Pycharm is warning me that `get_overloads` and `clear_overloads` is missing from `typing_extensions.pyi` 
I'm not sure if this is a pycharm issue or typing extensions

If this is an issue with typing extensions, Im happy to make a PR

**Comment by pseudo-rnd-thoughts** [comment]
Closing as typeshed just needed updating
`pip install --upgrade types-six types-requests`

**Comment by JelleZijlstra** [comment]
Not sure how upgrading the stubs for six or requests made a difference here, but glad your issue was resolved.
