### ISSUE TITLE
Initial runtime support for PEP 696 (TypeVarLike defaults)

### ISSUE THREAD

**Issue by cdce8p** [python/typing_extensions#75]
I would like to start adding runtime support for [PEP 696 ](https://peps.python.org/pep-0696/). If the `default` parameter is added to `TypeVar`, `ParamSpec`, and `TypeVarTuple`, type checkers could start adding provisional support.

As I understand it, there exists a reference implementation for mypy already. It would be awesome, if we could start using that even before the PEP is formally accepted. With the 0.981 release for example, mypy added support for [PEP 692](https://peps.python.org/pep-0692/) although it hasn't been approved yet.

Before I start working on it, would a PR be accepted?

/CC: @Gobot1234

**Comment by JelleZijlstra** [comment]
Yes, we'll accept support for PEP 696 in typing-extensions, as we generally accept implementations of PEPs that have been assigned a number.

**Comment by Gobot1234** [comment]
Not that it should be that important at runtime but there is currently a PR open that should be treated as the most up to date version of PEP 696 https://pep-previews--2777.org.readthedocs.build/pep-0696. Thanks for taking this on BTW :)

**Comment by cdce8p** [comment]
I've opened #77 with initial support for the `default` parameter.
