### ISSUE TITLE
Consider backporting `isinstance`/`issubclass` from PEP 604

### ISSUE THREAD

**Issue by gschaffner** [python/typing_extensions#87]
(https://docs.python.org/3.10/library/stdtypes.html#types-union)

I haven't been able to find a given reason for this in the readme or the issue tracker. If this is intentionally left un-backported, it could be helpful to add a note to the readme about it.

**Comment by JelleZijlstra** [comment]
The primary reason is that it's not part of typing.py. PEP 604 required many changes in the core language (e.g., adding `|` support to `type`) that typing-extensions can't provide.

**Comment by gschaffner** [comment]
Hi, thank you for the reply!

In my head, I wasn't including `type.__or__` as a `Union` feature to consider backporting—it seems `type.__or__` can only be implemented as a language feature. What I meant was `issubclass`, `isinstance`, and `==` support for `Union`. I haven't thought about it *too* much, but I figured it might be possible to backport those via `__subclasscheck__`, `__instancecheck__`, and `__eq__`.

**Comment by JelleZijlstra** [comment]
`__eq__` already exists on `typing.Union` in 3.9. We could backport `isinstance`/`issubclass` support to 3.7–3.9 if somebody asks for it, but personally I don't think it's that valuable.
