### ISSUE TITLE
Why is "typing_extensions" package installed twice on my conda environemment

### ISSUE THREAD

**Issue by IndigoWizard** [python/typing_extensions#88]
The "typing_extensions" package is listed twice successively in my conda environment.
I tried to delete it, ran "`conda remove typing_extensions`", it did but after checking conda list both packages are still there, and still figuring in the list twice

![image](https://user-images.githubusercontent.com/43890965/196005007-09125adb-4d90-46c2-9e81-5e2a7d42d0a2.png)

**Comment by gvanrossum** [comment]
This is a question better asked of the package management tool you're using. If there's an answer I'm sure that it's not specific to typing_extensions.
