### ISSUE TITLE
Add SupportsLessThan to typing and typing_extensions

### ISSUE THREAD

**Issue by hauntsaninja** [python/typing_extensions#9]
The latest version of mypy / typeshed uses a protocol for things passed to sorted / sort. As measured by mypy_primer, this was a fairly disruptive change. To correctly type some usage of sort / sorted, you need the protocol, and it's pretty hard for users to figure this out, eg: https://github.com/elastic/eland/pull/283#discussion_r504058169
Adding the protocol to typing / typing_extensions would make this solution more discoverable and involve less end user protocol redefinition boilerplate when used.

**Comment by JelleZijlstra** [comment]
Closing this as our current policy is to add only types that are in `typing`. #6 proposes changing that.

In addition, typeshed no longer has a `SupportsLessThan` type.
